services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: gw-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: gw-kafka
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  order-postgres:
    image: postgres:16
    container_name: order-postgres
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders
    ports:
      - "5433:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data

  payments-postgres:
    image: postgres:16
    container_name: payments-postgres
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments
    ports:
      - "5435:5432"
    volumes:
      - payments_db_data:/var/lib/postgresql/data

  order-service:
    image: arifruette/order-service:0.0.1
    container_name: order-service
    depends_on: [ order-postgres, kafka ]
    environment:
      APP_DB_URL: jdbc:postgresql://order-postgres:5432/orders
      APP_DB_USER: orders
      APP_DB_PASSWORD: orders
      APP_KAFKA_BOOTSTRAP: kafka:9092
    ports:
      - "8081:8080"
    restart: unless-stopped

  payments-service:
    image: arifruette/payments-service:0.0.1
    container_name: payments-service
    depends_on: [ payments-postgres, kafka ]
    environment:
      APP_DB_URL: jdbc:postgresql://payments-postgres:5432/payments
      APP_DB_USER: payments
      APP_DB_PASSWORD: payments
      APP_KAFKA_BOOTSTRAP: kafka:9092
    ports:
      - "8082:8080"
    restart: unless-stopped

  api-gateway:
    build: .
    container_name: api-gateway
    depends_on: [ order-service, payments-service ]
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      SERVICES_ORDER_BASEURL: http://order-service:8080
      SERVICES_PAYMENTS_BASEURL: http://payments-service:8080
    restart: unless-stopped

  frontend:
    image: arifruette/payments-frontend:0.0.1
    container_name: frontend
    depends_on: [ api-gateway ]
    ports:
      - "3000:80"
    restart: unless-stopped


volumes:
  order_db_data:
  payments_db_data:
